#!/bin/sh

#Default values
#export ARTIFACTORY_BIN_HOME=/var/lib/artifactory
#export TOMCAT_HOME=/opt/artifactory/tomcat
#export ARTIFACTORY_CONSOLE=${ARTIFACTORY_HOME}/logs/consoleout.log
#export CATALINA_PID=/var/lib/artifactory/artifactory.pid

export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/jre
export JAVA_OPTIONS="-server -Xms1g -Xmx1g -Xss256k -XX:PermSize=128m -XX:MaxPermSize=128m -XX:NewSize=384m -XX:MaxNewSize=384m"
export ARTIFACTORY_HOME=/opt/artifactory-2.4.2
export ARTIFACTORY_USER=artifactory